/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author pedrosaura
 */
public class Ej8_23 extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_23
     */
    // Arrays para almacenar los precios y los seleccionados
    private static double[] arrPrecios = {3.5, 1.0, 1.5, 1.75, 1.5, 2.0, 1.25, 5.75};
   
    private static boolean[] arrSeleccionados = new boolean[8];
    
    public Ej8_23() {
        initComponents();
        btnReset.requestFocus();
    }
    
    private void updateSeleccionados(int index, boolean isSelected) 
    {
        arrSeleccionados[index] = isSelected;
    }

    private void seleccionarMenu(int[] indices) 
    {
        //resetSeleccionados();
        for (int index : indices) 
        {
            arrSeleccionados[index] = true;
            actualizarCheckbox(index, true);
        }
    }

    

    private void actualizarCheckbox(int index, boolean isSelected) 
    {
        switch (index) 
        {
//            case 0 -> chkHamb.setSelected(isSelected);
//            case 1 -> chkPata.setSelected(isSelected);
//            case 2 -> chkRefr.setSelected(isSelected);
//            case 3 -> chkCerv.setSelected(isSelected);
//            case 4 -> chkPeti.setSelected(isSelected);
//            case 5 -> chkHela.setSelected(isSelected);
//            case 6 -> chkCafe.setSelected(isSelected);
//            case 7 -> chkHambDobl.setSelected(isSelected);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlatos = new javax.swing.JPanel();
        chkHamb = new javax.swing.JCheckBox();
        chkPata = new javax.swing.JCheckBox();
        chkRefr = new javax.swing.JCheckBox();
        chkCerv = new javax.swing.JCheckBox();
        chkPeti = new javax.swing.JCheckBox();
        chkHela = new javax.swing.JCheckBox();
        chkCafe = new javax.swing.JCheckBox();
        chkHambDobl = new javax.swing.JCheckBox();
        txfHamb = new javax.swing.JTextField();
        txfPata = new javax.swing.JTextField();
        txfRefr = new javax.swing.JTextField();
        txfCerv = new javax.swing.JTextField();
        txfPeti = new javax.swing.JTextField();
        txfHela = new javax.swing.JTextField();
        txfCafe = new javax.swing.JTextField();
        txfHambDobl = new javax.swing.JTextField();
        panMenus = new javax.swing.JPanel();
        rdbInfa = new javax.swing.JRadioButton();
        rdbJove = new javax.swing.JRadioButton();
        rdbMaxi = new javax.swing.JRadioButton();
        btnPedido = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txfTotal = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comanda");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panPlatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Platos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(255, 51, 0))); // NOI18N

        chkHamb.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkHamb.setSelected(true);
        chkHamb.setText("Hamburguesa");
        chkHamb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHambItemStateChanged(evt);
            }
        });
        chkHamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHambActionPerformed(evt);
            }
        });

        chkPata.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkPata.setSelected(true);
        chkPata.setText("Patatas Fritas");
        chkPata.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPataItemStateChanged(evt);
            }
        });

        chkRefr.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkRefr.setSelected(true);
        chkRefr.setText("Refresco");
        chkRefr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkRefrItemStateChanged(evt);
            }
        });

        chkCerv.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkCerv.setText("Cerveza");
        chkCerv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCervItemStateChanged(evt);
            }
        });

        chkPeti.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkPeti.setText("Petit");
        chkPeti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPetiItemStateChanged(evt);
            }
        });

        chkHela.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkHela.setSelected(true);
        chkHela.setText("Helado");
        chkHela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHelaItemStateChanged(evt);
            }
        });

        chkCafe.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkCafe.setText("Café");
        chkCafe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCafeItemStateChanged(evt);
            }
        });

        chkHambDobl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        chkHambDobl.setText("Hamb. Doble");
        chkHambDobl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHambDoblItemStateChanged(evt);
            }
        });

        txfHamb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfHamb.setText("3.5");
        txfHamb.setEnabled(false);

        txfPata.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPata.setText("1");
        txfPata.setEnabled(false);

        txfRefr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfRefr.setText("1.5");
        txfRefr.setEnabled(false);

        txfCerv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfCerv.setText("1.75");
        txfCerv.setEnabled(false);
        txfCerv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCervActionPerformed(evt);
            }
        });

        txfPeti.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPeti.setText("1.5");
        txfPeti.setEnabled(false);

        txfHela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfHela.setText("2");
        txfHela.setEnabled(false);

        txfCafe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfCafe.setText("1.25");
        txfCafe.setEnabled(false);

        txfHambDobl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfHambDobl.setText("5.75");
        txfHambDobl.setEnabled(false);

        javax.swing.GroupLayout panPlatosLayout = new javax.swing.GroupLayout(panPlatos);
        panPlatos.setLayout(panPlatosLayout);
        panPlatosLayout.setHorizontalGroup(
            panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPlatosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHambDobl)
                    .addComponent(chkCafe)
                    .addComponent(chkHela)
                    .addComponent(chkPeti)
                    .addComponent(chkCerv)
                    .addComponent(chkRefr)
                    .addComponent(chkPata)
                    .addComponent(chkHamb))
                .addGap(18, 18, 18)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfCerv)
                    .addComponent(txfCafe)
                    .addComponent(txfHambDobl)
                    .addComponent(txfHamb)
                    .addComponent(txfPata)
                    .addComponent(txfRefr)
                    .addComponent(txfPeti)
                    .addComponent(txfHela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPlatosLayout.setVerticalGroup(
            panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPlatosLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHamb)
                    .addComponent(txfHamb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPata)
                    .addComponent(txfPata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRefr)
                    .addComponent(txfRefr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCerv)
                    .addComponent(txfCerv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPeti)
                    .addComponent(txfPeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHela)
                    .addComponent(txfHela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCafe)
                    .addComponent(txfCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHambDobl)
                    .addComponent(txfHambDobl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        panMenus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menús", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(255, 51, 0))); // NOI18N

        rdbInfa.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rdbInfa.setText("Infantil");
        rdbInfa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbInfaItemStateChanged(evt);
            }
        });
        rdbInfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbInfaActionPerformed(evt);
            }
        });

        rdbJove.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rdbJove.setSelected(true);
        rdbJove.setText("Joven");
        rdbJove.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbJoveItemStateChanged(evt);
            }
        });
        rdbJove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbJoveActionPerformed(evt);
            }
        });

        rdbMaxi.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rdbMaxi.setText("Maxi");
        rdbMaxi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMaxiItemStateChanged(evt);
            }
        });
        rdbMaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaxiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenusLayout = new javax.swing.GroupLayout(panMenus);
        panMenus.setLayout(panMenusLayout);
        panMenusLayout.setHorizontalGroup(
            panMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbInfa)
                    .addComponent(rdbMaxi)
                    .addComponent(rdbJove))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panMenusLayout.setVerticalGroup(
            panMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenusLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rdbInfa)
                .addGap(32, 32, 32)
                .addComponent(rdbJove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(rdbMaxi)
                .addGap(17, 17, 17))
        );

        btnPedido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPedido.setMnemonic('P');
        btnPedido.setText("Pedido");
        btnPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPedidoFocusGained(evt);
            }
        });
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnReset.setMnemonic('P');
        btnReset.setText("Reset");
        btnReset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnResetFocusGained(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTotal.setText("Total");

        txfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfTotal.setText("8,0");
        txfTotal.setEnabled(false);
        txfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTotalActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPedido)
                            .addComponent(btnReset))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir))
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkHambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHambActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHambActionPerformed

    private void txfCervActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCervActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCervActionPerformed

    private void txfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTotalActionPerformed

    private void btnResetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnResetFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetFocusGained

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        for (int k = 0; k < arrSeleccionados.length; k = k + 1) 
        {
            arrSeleccionados[k] = false;
            actualizarCheckbox(k, false);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPedidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidoFocusGained

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        // TODO add your handling code here:
        double total = 0;
        
        boolean algunSeleccionado = false;

        for (int k  = 0; k  < arrSeleccionados.length; k = k + 1) 
        {
            if (arrSeleccionados[k ]) 
            {
                total += arrPrecios[k ];
                algunSeleccionado = true;
            }
        }

        if (!algunSeleccionado) 
        {
            JOptionPane.showMessageDialog(this, "Ningún plato seleccionado.", "Error en platos", JOptionPane.ERROR_MESSAGE);
            chkHamb.requestFocus();
            txfTotal.setText("0,00");
        } 
        else 
        {
            txfTotal.setText(String.format("%.2f", total).replace('.', ','));
        }
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void rdbInfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInfaActionPerformed
        // TODO add your handling code here:
        chkHamb.setSelected(true);
        chkPata.setSelected(false);
        chkRefr.setSelected(true);
        chkCerv.setSelected(false);
        chkPeti.setSelected(true);
        chkHela.setSelected(false);
        chkCafe.setSelected(false);
        chkHambDobl.setSelected(false);
    }//GEN-LAST:event_rdbInfaActionPerformed

    private void rdbJoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbJoveActionPerformed
        // TODO add your handling code here:
        chkHamb.setSelected(true);
        chkPata.setSelected(false);
        chkRefr.setSelected(true);
        chkCerv.setSelected(false);
        chkPeti.setSelected(false);
        chkHela.setSelected(true);
        chkCafe.setSelected(false);
        chkHambDobl.setSelected(false);
    }//GEN-LAST:event_rdbJoveActionPerformed

    private void rdbMaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaxiActionPerformed
        // TODO add your handling code here:
        chkHamb.setSelected(false);
        chkPata.setSelected(true);
        chkRefr.setSelected(true);
        chkCerv.setSelected(false);
        chkPeti.setSelected(false);
        chkHela.setSelected(true);
        chkCafe.setSelected(true);
        chkHambDobl.setSelected(true);
    }//GEN-LAST:event_rdbMaxiActionPerformed

    private void rdbInfaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbInfaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbInfaItemStateChanged

    private void rdbJoveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbJoveItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbJoveItemStateChanged

    private void rdbMaxiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMaxiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaxiItemStateChanged

    private void chkHambItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHambItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[0] = chkHamb.isSelected();
    }//GEN-LAST:event_chkHambItemStateChanged

    private void chkPataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPataItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[1] = chkPata.isSelected();
    }//GEN-LAST:event_chkPataItemStateChanged

    private void chkRefrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkRefrItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[2] = chkRefr.isSelected();
    }//GEN-LAST:event_chkRefrItemStateChanged

    private void chkCervItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCervItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[3] = chkCerv.isSelected();
    }//GEN-LAST:event_chkCervItemStateChanged

    private void chkPetiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPetiItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[4] = chkPeti.isSelected();
    }//GEN-LAST:event_chkPetiItemStateChanged

    private void chkHelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHelaItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[5] = chkHela.isSelected();
    }//GEN-LAST:event_chkHelaItemStateChanged

    private void chkCafeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCafeItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[6] = chkCafe.isSelected();
    }//GEN-LAST:event_chkCafeItemStateChanged

    private void chkHambDoblItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHambDoblItemStateChanged
        // TODO add your handling code here:
        arrSeleccionados[7] = chkHambDobl.isSelected();
    }//GEN-LAST:event_chkHambDoblItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkCafe;
    private javax.swing.JCheckBox chkCerv;
    private javax.swing.JCheckBox chkHamb;
    private javax.swing.JCheckBox chkHambDobl;
    private javax.swing.JCheckBox chkHela;
    private javax.swing.JCheckBox chkPata;
    private javax.swing.JCheckBox chkPeti;
    private javax.swing.JCheckBox chkRefr;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panMenus;
    private javax.swing.JPanel panPlatos;
    private javax.swing.JRadioButton rdbInfa;
    private javax.swing.JRadioButton rdbJove;
    private javax.swing.JRadioButton rdbMaxi;
    private javax.swing.JTextField txfCafe;
    private javax.swing.JTextField txfCerv;
    private javax.swing.JTextField txfHamb;
    private javax.swing.JTextField txfHambDobl;
    private javax.swing.JTextField txfHela;
    private javax.swing.JTextField txfPata;
    private javax.swing.JTextField txfPeti;
    private javax.swing.JTextField txfRefr;
    private javax.swing.JTextField txfTotal;
    // End of variables declaration//GEN-END:variables
}
